export const MIHOMO_IPC_INVOKE_CHANNELS = {
  checkMihomoLatestVersion: 'checkMihomoLatestVersion',
  mihomoChangeProxy: 'mihomoChangeProxy',
  mihomoCloseAllConnections: 'mihomoCloseAllConnections',
  mihomoCloseConnection: 'mihomoCloseConnection',
  mihomoConfig: 'mihomoConfig',
  mihomoDnsQuery: 'mihomoDnsQuery',
  mihomoGroupDelay: 'mihomoGroupDelay',
  mihomoGroups: 'mihomoGroups',
  mihomoProxies: 'mihomoProxies',
  mihomoProxyDelay: 'mihomoProxyDelay',
  mihomoProxyProviders: 'mihomoProxyProviders',
  mihomoRuleProviders: 'mihomoRuleProviders',
  mihomoRules: 'mihomoRules',
  mihomoToggleRuleDisabled: 'mihomoToggleRuleDisabled',
  mihomoUnfixedProxy: 'mihomoUnfixedProxy',
  mihomoUpdateProxyProviders: 'mihomoUpdateProxyProviders',
  mihomoUpdateRuleProviders: 'mihomoUpdateRuleProviders',
  mihomoUpgrade: 'mihomoUpgrade',
  mihomoUpgradeGeo: 'mihomoUpgradeGeo',
  mihomoUpgradeUI: 'mihomoUpgradeUI',
  mihomoVersion: 'mihomoVersion',
  patchMihomoConfig: 'patchMihomoConfig',
  restartCore: 'restartCore',
  restartMihomoConnections: 'restartMihomoConnections'
} as const
