export const DIRECT_RULE_TARGET = 'DIRECT'
export const REJECT_RULE_TARGET = 'REJECT'
export const COMMON_RULE_TARGETS = [DIRECT_RULE_TARGET, REJECT_RULE_TARGET, 'REJECT-DROP', 'PASS']
export const BUILT_IN_RULE_TARGETS = [...COMMON_RULE_TARGETS, 'PASS-RULE', 'GLOBAL']
export const CHAIN_BASE_TARGETS = [DIRECT_RULE_TARGET, REJECT_RULE_TARGET]
